name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - uses: actions/checkout@v3 #https://github.com/actions/checkout

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3 #https://github.com/actions/setup-node
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Testing
      run: npm test