name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    install-and-test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [17.x]

      steps:
        - uses: actions/checkout@master

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install packages
          run: yarn install --frozen-lockfile
        
        - name: Test
          run: npm test
          env:
            CI: true
     
            
        - name: Checkout 
          uses: actions/checkout@v2
          
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/client_numer:latest
        - name: Set-up Node
          uses: actions/setup-node@v1
          with:
            node-version: "17.x"
        - run: npm install react-scripts
        - run: npm install

#         - run: npm run build
        - run: npm test
        - name: Deploy
          uses: crazy-max/ghaction-github-pages@v1
          with: 
            target_branch: gh-pages
            build_dir: build
          env:
            GITHUB_TOKEN: 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
        
        
        
        

  
        
